#+title: Emacs Rime 基本安装与使用方法

** 依赖
   - Emacs 26.1+ ，且需启用动态支持模块。
   - emacs-rime 会自动构建所需的动态模块，这需要 ~make~ 和 ~gcc~ 可用。
*** 如何获得支持动态模块的 Emacs ？
#+html: <details>
#+html: <summary>切换折叠</summary>
**** Linux
Linux 各主要发行版自带 emacs 默认已启用动态模块支持。

**** MacOS
***** emacs-plus 默认启用 ~--with-modules~ 选项，使用 homebrew 安装命令如下：
#+BEGIN_SRC shell
brew tap d12frosted/emacs-plus
brew install emacs-plus
#+END_SRC

***** emacs-mac 安装时需要启用 ~--with-modules~ 选项，使用 homebrew 安装命令如下 :
#+BEGIN_SRC shell
brew tap railwaycat/emacsmacport
brew install emacs-mac --with-modules
#+END_SRC

**** 手工编译

使用 ~--with-modules~ 选项.

#+html: </details>

** 安装 librime

*** Linux

**** ArchLinux/Manjaro

     #+begin_src emacs-lisp
       sudo pacman -S librime
     #+end_src

**** Debian/Ubuntu

     #+begin_src emacs-lisp
       sudo apt install librime-dev
     #+end_src

     请注意 ~librime-dev~ 的版本，如果在1.5.3以下，则需要自行编译。

     #+begin_src emacs-lisp
       sudo apt install git build-essential cmake libboost-all-dev libgoogle-glog-dev libleveldb-dev libmarisa-dev libopencc-dev libyaml-cpp-dev libgtest-dev
       git clone https://github.com/rime/librime.git ~/.emacs.d/librime
       cd ~/.emacs.d/librime
       make
       sudo make install
     #+end_src

**** Fedora

     #+begin_src emacs-lisp
       sudo dnf install librime-devel emacs-devel
     #+end_src

**** openSUSE

     #+begin_src emacs-lisp
       sudo zypper install librime-devel emacs-el
     #+end_src

*** MacOS
    1. 先安装[[https://rime.im/download/][鼠须管]]，里面有输入法方案。
    2. 然后直接下载编译好的librime的Release版本。
    3. 如果后续安装了鼠须管的升级版本，请查阅它的[[https://github.com/rime/squirrel/blob/master/CHANGELOG.md][更新日志]]，将librime也升级到相匹配的版本。

    #+BEGIN_SRC bash
      curl -L -O https://github.com/rime/librime/releases/download/1.7.1/rime-1.7.1-osx.zip
      unzip rime-1.7.1-osx.zip -d ~/.emacs.d/librime
      rm -rf rime-1.7.1-osx.zip
    #+END_SRC

    如果MacOS Gatekeeper阻止第三方软件运行，可以暂时关闭它：

    #+begin_src bash
      sudo spctl --master-disable
      # later: sudo spctl --master-enable
    #+end_src

*** Windows

**** 使用 scoop

    可以使用 [[https://scoop.sh][scoop]] 来安装自动构建所需的依赖。

    #+begin_src powershell
      scoop install gcc
      scoop bucket add wsw0108 https://github.com/wsw0108/scoop-bucket.git
      scoop install librime
    #+end_src

**** 使用 msys2

    使用 [[https://www.msys2.org/][msys2]] 构建所需的依赖。

    #+begin_src bash
      pacman -S pactoys base-devel
      pacboy -S librime:x librime-data:x emacs:x toolchain:x
      ln -s /mingw64/share/opencc/* /mingw64/share/rime-data/opencc # Fix the Simplified Chinese input
    #+end_src

    在 mingw64 环境中启动 emacs 来获取正确的 =SHELL= 环境变量，用来在 Emacs 内构建 librime-emacs 以及  =MSYSTEM_PREFIX= 环境变量来设置 ~rime-share-data-dir~ 变量。

*** 编译时无法找到 rime_api.h ？
#+html: <details>
#+html: <summary>切换折叠</summary>
必须设置 ~rime-librime-root~ 参照安装方法中的说明。

#+html: </details>
*** 编译时无法找到 emacs-module.h ？
#+html: <details>
#+html: <summary>切换折叠</summary>

如果自己编译 Emacs 且没有安装到标准目录（/usr/, /usr/local/），
*必须* 指定 ~rime-emacs-module-header-root~ 。

在 ~:custom~ 中加入如下内容.

(假设将 Emacs 安装到了 ~/emacs)

#+BEGIN_SRC emacs-lisp
(rime-emacs-module-header-root "~/emacs/include")
#+END_SRC

#+html: </details>
** 最小配置

   Emacs Rime 已发布到 Melpa 。

   #+begin_src emacs-lisp
     (use-package rime
       :custom
       (default-input-method "rime"))
   #+end_src

*** 使用 Straight
#+html: <details>
#+html: <summary>切换折叠</summary>
#+BEGIN_SRC emacs-lisp
  (use-package rime
    :straight (rime :type git
                    :host github
                    :repo "DogLooksGood/emacs-rime"
                    :files ("*.el" "Makefile" "lib.c"))
    :custom
    (default-input-method "rime"))
#+END_SRC
#+html: </details>

*** 使用 Quelpa
#+html: <details>
#+html: <summary>切换折叠</summary>
#+BEGIN_SRC emacs-lisp
  (use-package rime
    :quelpa (rime :fetcher github
                  :repo "DogLooksGood/emacs-rime"
                  :files ("*.el" "Makefile" "lib.c"))
    :custom
    (default-input-method "rime"))
#+END_SRC
#+html: </details>

*** 注意（MacOS）
*NOTE* 如果你在 MacOS 上或是选择自己编译 librime （没有放在系统路径中）， *必须* 指定 ~rime-librime-root~ 。

在 ~:custom~ 中加入如下内容.

(假设将 librime 解压到了 ~/.emacs.d/librime)

#+BEGIN_SRC emacs-lisp
  (rime-librime-root "~/.emacs.d/librime/dist")
#+END_SRC

** 激活 Rime 输入法

   使用 ~toggle-input-method~ 来激活，默认快捷键为 ~C-\~
